- name: Comment out motd news
  ansible.builtin.replace:
    path: /etc/default/motd-news  # Assuming this is the file you want to modify
    regexp: '^ENABLED=1'          # Example regex, adjust as needed
    replace: 'ENABLED=0'          # Example replacement, adjust as needed

